FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/website/package.json ./apps/website/package.json
COPY apps/server/package.json ./apps/server/package.json

RUN pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "--filter", "@teddy/website", "dev"]
